version: '3'

services:
    serv:
        restart: always
        image: fred1653/imageserv
        container_name: serv
        depends_on: 
            - postgres:
                condition: service_healthy
        ports:
            - 80:8000
        links:
            - postgres
        volumes: 
            - ~/imageserv_data:/data/images
    postgres:
        restart: always
        image: postgres:13
        container_name: postgres
        expose:
            - 5432
        ports:
            - "5432:5432"
        volumes:
            - ~/postgres_data:/var/lib/postgresql
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres